networks:
  laravel:

volumes:
  postgres:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8088:80"
    volumes:
      - ./src:/var/www/html
      - ./docker/volumes/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - postgres
    networks:
      - laravel

  postgres:
    image: postgres:13.7-alpine
    container_name: postgres
    restart: on-failure
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgres
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: homestead
      POSTGRES_DB: homestead
    networks:
      - laravel

  php:
    image: migonos/php:8.1.6-fpm-pdopgsql_composer-bullseye
    container_name: php
    volumes:
      - ./src:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - laravel
    user: ${UID}:${GID}
